const countryName = {
  inr: "India",
  usd: "United States",
  aud: "Australia",
  cad: "Canada",
  gbp: "United Kingdom",
  eur: "Eurozone",
  chf: "Switzerland",
  jpy: "Japan",
  krw: "South Korea",
  rub: "Russia",
  brl: "Brazil",
  cny: "China",
  mxn: "Mexico",
  sek: "Sweden",
  nzd: "New Zealand",
  zar: "South Africa",
  try: "Turkey",
  ars: "Argentina",
  sgd: "Singapore",
  aed: "United Arab Emirates",
  egp: "Egypt",
  thb: "Thailand",
  idr: "Indonesia",
  myr: "Malaysia",
  php: "Philippines",
  vnd: "Vietnam",
  kes: "Kenya",
  ngn: "Nigeria",
  pkr: "Pakistan",
  bdt: "Bangladesh",
  lkr: "Sri Lanka",
  ils: "Israel",
  hkd: "Hong Kong",
  uah: "Ukraine",
  clp: "Chile",
  pen: "Peru",
};
